name: Laravel Teste

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  laravel-test:
    name: Laravel test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4]
        laravel: [^8.0]

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: post_max_size=256M, max_execution_time=180
          tools: composer:v2, php-cs-fixer, phpunit
          coverage: none    
      
      - name: Copiar .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Instalando as dependencias do Composer
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Gerar a chave do Laravel
        run: php artisan key:generate

      - name: Atribuindo Permissões aos Diretorios para o Laravel
        run: chmod -R 777 storage bootstrap/cache

      - name: Criando a Base de Dados para executar os testes
        run: |
          mkdir -p database
          touch database/database.sqlite
          
      - name: Executando os tests (Unit e Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit --verbose
      