name: Tests
on:
  push:
    branches-ignore:
      - deploy

    tags-ignore:
      - 'v*'

jobs:
  tests:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.4', '8.0' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, dom, fileinfo, mysql, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: xdebug

      - name: Install composer dependencies
        run: composer install --ignore-platform-reqs --no-progress --prefer-dist --optimize-autoloader

      - name: Prepare the application
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
          php artisan config:clear

      - name: Creating database to run the tests
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run Migration
        run: php artisan migrate -v
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      - name: Run PHP Codesniffer
        run: vendor/bin/phpcs

      - name: Run tests via PHPUnit
        run: vendor/bin/phpunit --verbose --coverage-text
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
